// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Resolvers
{
    public class GeneratedResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new GeneratedResolver();

        private GeneratedResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = GeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class GeneratedResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> lookup;

        static GeneratedResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(27)
            {
                { typeof(global::System.Collections.Generic.List<global::RoomElement>), 0 },
                { typeof(global::System.Collections.Generic.List<global::UserElement>), 1 },
                { typeof(global::AutoLoginPacket), 2 },
                { typeof(global::ChatPacket), 3 },
                { typeof(global::CreateRoomPacket), 4 },
                { typeof(global::JoinRoomPacket), 5 },
                { typeof(global::JoinRoomResponsePacket), 6 },
                { typeof(global::LeaveRoomPacket), 7 },
                { typeof(global::LeaveRoomResponsePacket), 8 },
                { typeof(global::ListRoomPacket), 9 },
                { typeof(global::ListRoomResponsePacket), 10 },
                { typeof(global::LoginPacket), 11 },
                { typeof(global::LoginResponsePacket), 12 },
                { typeof(global::MovePacket), 13 },
                { typeof(global::PacketBase), 14 },
                { typeof(global::ReadyPacket), 15 },
                { typeof(global::ReadyResponsePacket), 16 },
                { typeof(global::RegisterPacket), 17 },
                { typeof(global::RegisterResponsePacket), 18 },
                { typeof(global::RoomElement), 19 },
                { typeof(global::RoomInfoPacket), 20 },
                { typeof(global::StartGamePacket), 21 },
                { typeof(global::SwitchRolePacket), 22 },
                { typeof(global::SwitchRoleResponsePacket), 23 },
                { typeof(global::UdpConnectPacket), 24 },
                { typeof(global::UdpPacketBase), 25 },
                { typeof(global::UserElement), 26 },
            };
        }

        internal static object GetFormatter(global::System.Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new global::MessagePack.Formatters.ListFormatter<global::RoomElement>();
                case 1: return new global::MessagePack.Formatters.ListFormatter<global::UserElement>();
                case 2: return new MessagePack.Formatters.AutoLoginPacketFormatter();
                case 3: return new MessagePack.Formatters.ChatPacketFormatter();
                case 4: return new MessagePack.Formatters.CreateRoomPacketFormatter();
                case 5: return new MessagePack.Formatters.JoinRoomPacketFormatter();
                case 6: return new MessagePack.Formatters.JoinRoomResponsePacketFormatter();
                case 7: return new MessagePack.Formatters.LeaveRoomPacketFormatter();
                case 8: return new MessagePack.Formatters.LeaveRoomResponsePacketFormatter();
                case 9: return new MessagePack.Formatters.ListRoomPacketFormatter();
                case 10: return new MessagePack.Formatters.ListRoomResponsePacketFormatter();
                case 11: return new MessagePack.Formatters.LoginPacketFormatter();
                case 12: return new MessagePack.Formatters.LoginResponsePacketFormatter();
                case 13: return new MessagePack.Formatters.MovePacketFormatter();
                case 14: return new MessagePack.Formatters.PacketBaseFormatter();
                case 15: return new MessagePack.Formatters.ReadyPacketFormatter();
                case 16: return new MessagePack.Formatters.ReadyResponsePacketFormatter();
                case 17: return new MessagePack.Formatters.RegisterPacketFormatter();
                case 18: return new MessagePack.Formatters.RegisterResponsePacketFormatter();
                case 19: return new MessagePack.Formatters.RoomElementFormatter();
                case 20: return new MessagePack.Formatters.RoomInfoPacketFormatter();
                case 21: return new MessagePack.Formatters.StartGamePacketFormatter();
                case 22: return new MessagePack.Formatters.SwitchRolePacketFormatter();
                case 23: return new MessagePack.Formatters.SwitchRoleResponsePacketFormatter();
                case 24: return new MessagePack.Formatters.UdpConnectPacketFormatter();
                case 25: return new MessagePack.Formatters.UdpPacketBaseFormatter();
                case 26: return new MessagePack.Formatters.UserElementFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1649 // File name should match first type name
